spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/weatherstats
    username: statsuser
    password: statspass
jpa:
  hibernate:
    ddl-auto: update
properties:
  hibernate:
    dialect: org.hibernate.dialect.MariaDB10Dialect
    format_sql: true
    show-sql: true
server:
  port: 8082